"""Typed Protocol classes for Dhan adapter provider dependencies.

REF-07: Replaces untyped lambda providers with explicit Protocol interfaces.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class HttpProvider(Protocol):
    """Provides access to the Dhan HTTP client."""
    def get(self, path: str, **kwargs: Any) -> dict[str, Any]: ...
    def post(self, path: str, data: dict[str, Any] | None = None, **kwargs: Any) -> dict[str, Any]: ...
    def put(self, path: str, data: dict[str, Any] | None = None, **kwargs: Any) -> dict[str, Any]: ...
    def delete(self, path: str, **kwargs: Any) -> dict[str, Any]: ...


@runtime_checkable
class TokenProvider(Protocol):
    """Provides access to the auth token manager."""
    def get_token(self) -> str: ...


@runtime_checkable
class WsProvider(Protocol):
    """Provides access to the WebSocket client."""
    def subscribe(self, security_ids: list[tuple[str, str]], mode: str = "quote") -> None: ...
    def unsubscribe(self, security_ids: list[tuple[str, str]]) -> None: ...
    def subscribe_depth(self, security_ids: list[tuple[str, str]], level: int = 20) -> None: ...
    def unsubscribe_depth(self, security_ids: list[tuple[str, str]], level: int = 20) -> None: ...
    @property
    def subscription_count(self) -> int: ...
    @property
    def depth_subscription_count(self) -> int: ...
    @property
    def depth_subscription_count_20(self) -> int: ...
    @property
    def depth_subscription_count_200(self) -> int: ...
    @property
    def depth_capacity_remaining_20(self) -> int: ...
    @property
    def depth_capacity_remaining_200(self) -> int: ...
    @property
    def subscription_capacity_remaining(self) -> int: ...
    MAX_SUBSCRIBERS: int


@runtime_checkable
class ResolveFn(Protocol):
    """Resolves a symbol+exchange pair to (security_id, wire_segment)."""
    def __call__(self, symbol: str, exchange: str) -> tuple[str, str]: ...
